[tool.ruff]
target-version = "py312"
line-length = 80
indent-width = 4
output-format = "grouped"
show-fixes = true
required-version = ">=0.11.0,<0.12"
respect-gitignore = true
fix = true

[tool.ruff.lint]
ignore = ["E501"]
extend-select = [
    "E",
    "W",
    "ASYNC",
    "S",
    "B",
    "A",
    "C4",
    "DTZ",
    "LOG",
    "G",
    "PIE",
    "PYI",
    "SIM",
    "PTH",
    "I",
    "C90",
    "N",
    "UP"
    # "D"
]

[tool.ruff.lint.per-file-ignores]
# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
"tests/*" = ["E501", "DTZ", "S106"]

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"
